name: YOUR_APP_NAME
description: App Description
ignoreFiles: .git venv
modules:
- name: YOUR_MODULE_NAME
  language: python3.8
  web: django
  description: Module description
  functions:
  - name: YOUR_FUNCTION_NAME
    entry: wsgi.py
    description: the entry point for the function